Bookstore - Components
Bhekisile/Bookstore pull request #1
Opened 2023-08-17 17:14 UTC by Bhekisile

## Changes

- Created components

2023-08-17 17:40 UTC, gemmen29 requested changes
Hi @Bhekisile, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights 💯 
- No linters errors ✔️ 
- Descriptive pull request ✔️ 
- Descriptive commit messages ✔️ 

## Required Changes ♻️
_Check the comments under the review._

![](https://media.giphy.com/media/tKyrc0NTlEcGWdThp4/giphy.gif)

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-17 17:40 UTC, gemmen29 commented on src/components/RenderBooks.js
> +function RenderBooks() {
- [ ] Kindly create a list containing individual books as per this [requirement](https://github.com/microverseinc/curriculum-react-redux/blob/main/bookstore/project_init_project_wth_comps_v3_0.md#:~:text=Contains%20a%20list%20to%20renders%20individual%20books).

2023-08-17 17:40 UTC, gemmen29 commented on src/components/RenderBooks.js
> +  return (
- [ ] For rendering a single book, Kindly use the created component `Book.js` and pass the `title` and `author` as props to it.

2023-08-18 14:09 UTC, Strangeal approved these changes
Hi @Bhekisile, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExZjk5MjNhMmYyM2RjZmZmNWRkNjA3OWNmNGFhMjI4NDViOTg4N2UzNyZlcD12MV9pbnRlcm5hbF9naWZzX2dpZklkJmN0PXM/x3l1BWfB85i2uU8nKK/giphy.gif)



## Highlights
- Added book list ✅ 
- Used props ✅ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-18 14:17 UTC, merged