Use Redux in React components
Bhekisile/Bookstore pull request #3
Opened 2023-08-22 04:08 UTC by Bhekisile

## Changes

- Added initial state to booksSlice

2023-08-22 13:19 UTC, ShadyShawkat requested changes
## Hi @Bhekisile, 

Good job so far! 👍🏻 
There are some issues that you still need to work on to go to the next project but you are almost there!

## To Highlight
- Correct use of GitFlow ✔️ 
- Descriptive commit messages ✔️ 
- Professional looking pull request ✔️ 

![Image](https://media.giphy.com/media/UdaSUYClr92cjWpeVx/giphy.gif)

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-22 13:19 UTC, ShadyShawkat commented on src/components/BookForm.js
> +        </button>
- [ ] Clicking this button refreshes the page and doesn't add a book as the page is reloaded. Kindly fix this behavior.

2023-08-23 09:33 UTC, levy002 approved these changes
## Hello @Bhekisile 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![](https://media.giphy.com/media/jJQC2puVZpTMO4vUs0/giphy.gif)

## Highlights
- No linter error :heavy_check_mark: 
- Implemented the suggested changes :heavy_check_mark: 

## Status: APPROVED :fire:  :fire: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-23 09:33 UTC, levy002 commented on src/components/BookForm.js
> +// import PropTypes from 'prop-types';
- [OPTIONAL] KIndly make sure to remove all commented code in order to keep the code clean and professional.

2023-08-23 09:38 UTC, Bhekisile commented on src/components/BookForm.js
> +// import PropTypes from 'prop-types';
I will do so, thank you.

2023-08-23 09:38 UTC, merged